// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"
)

type Produto struct {
	ID       int32     `json:"id"`
	Nome     string    `json:"nome"`
	Preco    int32     `json:"preco"`
	CriadoEm time.Time `json:"criado_em"`
}
