// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduto(ctx context.Context, arg CreateProdutoParams) (Produto, error)
	DeleteProduto(ctx context.Context, id int32) error
	GetProduto(ctx context.Context, id int32) (Produto, error)
	GetProdutos(ctx context.Context) ([]Produto, error)
	UpdateProduto(ctx context.Context, arg UpdateProdutoParams) (Produto, error)
}

var _ Querier = (*Queries)(nil)
